### ISSUE TITLE
Request dataset

### ISSUE THREAD

**Issue by jisangXx** [akdd11/dt-radio-environment-novel-approach#1]
I am doing similar research and trying to experiment with the ray tracing method of the sionna library, but I have a problem when trying to plot the ROC with the generated dataset. Could you please share your original dataset? My email is 21011210368@stu.xidian.edu.cn

**Comment by akdd11** [comment]
Hi, the dataset is now uploaded [here](https://zenodo.org/doi/10.5281/zenodo.10512315). You can download the files and insert them in a `datasets` folder in the root folder (see updated readme, the folder should also occur when you clone the updated repo now).

**Comment by jisangXx** [comment]
I have run through the data set through my own attempts, but thank you for sharing even so. I benefited a lot from your code. I look forward to seeing your further progress on this.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akdd11/dt-radio-environment-novel-approach"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akdd11/dt-radio-environment-novel-approach] Request dataset (Issue #1)





 
Hi, the dataset is now uploaded here. You can download the files and insert them in a datasets folder in the root folder (see updated readme, the folder should also occur when you clone the updated repo now).
